from django.db import models
lang_choices = (
  ('af', 'Afrikaans'),
  ('ar', 'Arabic'),
  ('bg', 'Bulgarian'),
  ('bn', 'Bengali'),
  ('bs', 'Bosnian'),
  ('ca', 'Catalan'),
  ('cs', 'Czech'),
  ('da', 'Danish'),
  ('de', 'German'),
  ('el', 'Greek'),
  ('en', 'English'),
  ('es', 'Spanish'),
  ('et', 'Estonian'),
  ('fi', 'Finnish'),
  ('fr', 'French'),
  ('gu', 'Gujarati'),
  ('hi', 'Hindi'),
  ('hr', 'Croatian'),
  ('hu', 'Hungarian'),
  ('id', 'Indonesian'),
  ('is', 'Icelandic'),
  ('it', 'Italian'),
  ('iw', 'Hebrew'),
  ('ja', 'Japanese'),
  ('jw', 'Javanese'),
  ('km', 'Khmer'),
  ('kn', 'Kannada'),
  ('ko', 'Korean'),
  ('la', 'Latyn'),
  ('lv', 'Lets'),
  ('ml', 'Malayalam'),
  ('mr', 'Marathi'),
  ('ms', 'Malay'),
  ('my', 'Mayanmar (Burmese)'),
  ('ne', 'Nepali'),
  ('nl', 'Dutch'),
    ('no', 'Norwegian'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('ro', 'Romanian'),
    ('ru', 'Russian'),
    ('si', 'Sinhala'),
    ('sk', 'Slovak'),
    ('sq', 'Albanian'),
    ('sr', 'Serbian'),
    ('su', 'Sundanese'),
    ('sv', 'Swedish'),
    ('sw', 'Swahili'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('th', 'Thai'),
    ('tl', 'Filipino'),
    ('tr', 'Turkish'),
    ('uk', 'Ukrainian'),
    ('ur', 'Urdu'),
    ('vi', 'Vietnamese'),
    ('zh-CN', 'Chinese (Simplified)'),
    ('zh-TW', 'Chinese (Mandarin/Taiwan)'),
    ('zh', 'Chinese (Mandarin)')
)

# Create your models here.
class Speak(models.Model):
    content = models.TextField(blank = True)
    link_to_access = models.TextField(blank=True)
    img = models.ImageField(upload_to='images/', blank=True)
    language = models.CharField(max_length = 10, choices = lang_choices, default = 'en')
    
