# Generated by Django 4.2.4 on 2023-08-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Speak', '0002_alter_text_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Speak',
        ),
    ]
