# Generated by Django 5.0.2 on 2024-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speak', '0003_rename_text_speak'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='link_to_access',
            field=models.TextField(blank=True),
        ),
    ]
