# Generated by Django 5.0.2 on 2024-05-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speak', '0004_speak_link_to_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
