# Generated by Django 5.0.2 on 2024-05-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speak', '0005_speak_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speak',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
