# Generated by Django 5.0.2 on 2024-05-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speak', '0006_alter_speak_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabies'), ('bg', 'Bulgaars'), ('bn', 'Bengaals'), ('bs', 'Bosnies'), ('ca', 'Katalaans'), ('cs', 'Tsjeggies'), ('da', 'Deens'), ('de', 'Duits'), ('el', 'Grieks'), ('en', 'Engels'), ('es', 'Spaans'), ('et', 'Estnies'), ('fi', 'Fins'), ('fr', 'Frans'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('hr', 'Kroaties'), ('hu', 'Hongaars'), ('id', 'Indonesies'), ('is', 'Yslands'), ('it', 'Italiaans'), ('iw', 'Hebreeus'), ('ja', 'Japanees'), ('jw', 'Javaans'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Koreaans'), ('la', 'Latyn'), ('lv', 'Lets'), ('ml', 'Mallayalams'), ('mr', 'Marathi'), ('ms', 'Maleis'), ('my', 'Birmaans'), ('ne', 'Nepalees'), ('nl', 'Nederlands'), ('no', 'Noors'), ('pl', 'Pools'), ('pt', 'Portugees'), ('ro', 'Roemeens'), ('ru', 'Russies'), ('si', 'Sinhala'), ('sk', 'Slowaaks'), ('sq', 'Albanees'), ('sr', 'Serwies'), ('su', 'Soendanees'), ('sv', 'Sweeds'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tl', 'Filippyns'), ('tr', 'Turks'), ('uk', 'Oekraïens'), ('ur', 'Urdu'), ('vi', 'Viëtnamees'), ('zh-CN', 'Chinees (Vereenvoudig)'), ('zh-TW', 'Chinees (Mandarijn/Taiwan)'), ('zh', 'Chinees (Mandarijn)')], default='en', max_length=10),
        ),
    ]
